language: python
jobs:
    include:
        - python: "3.6"
          env: TOX_ENV=py36
        - python: "3.7"
          env: TOX_ENV=py37
        - python: "3.8"
          env: TOX_ENV=py38
        - python: "3.9"
          env: TOX_ENV=py39
notifications:
    email: false
install:
  - pip install -r requirements_dev.txt
script:
  - tox -e $TOX_ENV
